/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Raudhya Azzahra'
 */
public class login_user extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.KoneksiDatabase.BukaKoneksi();
    public login_user() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    private void bersih(){
        txtusername.setText("");
        txtpassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();
        lbl3 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(172, 97, 171));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKembali.setBackground(new java.awt.Color(255, 204, 0));
        btnKembali.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        lbl3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl3.setText("Username");
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtpassword.setBackground(new java.awt.Color(172, 97, 171));
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 168, -1));

        lbl4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl4.setText("Password");
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        btnLogin.setBackground(new java.awt.Color(255, 102, 102));
        btnLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        lbl2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl2.setText("Belum Punya akun?");
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        Register.setBackground(new java.awt.Color(0, 255, 204));
        Register.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        txtusername.setBackground(new java.awt.Color(172, 97, 171));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 168, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 330, 250));

        lbl1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 33)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("USER");
        jPanel4.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 100, -1));

        lbl5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setText("LOGIN");
        jPanel4.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtusername.getText();
        String password = txtpassword.getText();
        
        if ( username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Tidak boleh kosong!");
            return;
        }
        
        if (cn !=null){
            try{
                st = cn.createStatement();
                String login = "SELECT * FROM akun WHERE username='"+username+"' AND password='"+password+"'";
                rs = st.executeQuery(login);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Berhasil Login!!!");
                    this.setVisible(false);
                    new menu_user().setVisible(true);
                } else{
                    JOptionPane.showMessageDialog(null, "Username atau Password salah");
                    bersih();
                    return;
                }
                rs.close();
                st.close();
                cn.close();
                
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "SQL ERROR");
                e.printStackTrace();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error");
                e.printStackTrace();
            }
        }
//        String username = txtusername.getText();
//        String password = txtpassword.getText();
//
//        if (username.isEmpty() || password.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Tidak boleh kosong");
//            return;
//        }
//        
//        if (cn !=null){
//            try{
//                st = cn.createStatement();
//                String login = "SELECT * FROM akun WHERE username='"+username+"' AND password='"+password+"'";
//                rs = st.executeQuery(login);
//                if (rs.next()){
//                    JOptionPane.showMessageDialog(null, "Berhasil Login!!");
//                    this.setVisible(false);
//                    new menu_user().setVisible(true);
//                } else {
//                    JOptionPane.showMessageDialog(null, "Username atau Password salah");
//                }
//                rs.close();
//                st.close();
//                cn.close();
//            }catch (SQLException e){
//                JOptionPane.showMessageDialog(null, "SQL ERROR"+ e.getMessage());
//                e.printStackTrace();
//            }catch (Exception e){
//                JOptionPane.showMessageDialog(null, "ERROR");
//                e.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        new register().setVisible(true);
    }//GEN-LAST:event_RegisterActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed

    }//GEN-LAST:event_txtusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
