/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Raudhya Azzahra'
 */
public class menu_admin extends javax.swing.JFrame {
    
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.KoneksiDatabase.BukaKoneksi();
    
     public menu_admin() {
       initComponents();
       Tampil();
       setLocationRelativeTo(this);
    }

    
    public void bersih(){
        idB.setText("");
        nama.setText("");
        harga.setText("");
        asal.setText("");
        stok.setText("");
    }
    
    private void Tampil(){
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM bunga ORDER BY id");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("id");
            model.addColumn("nama");
            model.addColumn("warna");
            model.addColumn("asal");
            model.addColumn("harga");
            model.addColumn("stok");
            model.addColumn("jenis");
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()){
                Object [] data = {rs.getString("id"), rs.getString("nama"), rs.getString("warna"), rs.getString("asal"), rs.getString("harga"), rs.getString("stok"), rs.getString("jenis")};
                model.addRow(data);
                tblData.setModel(model);
            }
        }catch (Exception e){   
        }
    }
        
   
    /**
     * Creates new form menu_admin
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        idB = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        cmbWarna = new javax.swing.JComboBox<>();
        harga = new javax.swing.JTextField();
        asal = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox<>();
        stok = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(172, 97, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Bunga");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 33, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Bunga");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jenis Bunga");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stok Bunga");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADMIN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 114, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MENU");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 79, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 0, 0));
        btnBack.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Keluar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 26, -1, 31));

        idB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idBActionPerformed(evt);
            }
        });
        jPanel1.add(idB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 410, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 410, -1));

        cmbWarna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Merah", "Kuning", "Pink", "Ungu", "Putih", "Biru" }));
        cmbWarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbWarnaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 89, 115, -1));

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 410, -1));
        jPanel1.add(asal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 410, -1));

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segar", "Kering" }));
        cmbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisActionPerformed(evt);
            }
        });
        jPanel1.add(cmbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 115, -1));
        jPanel1.add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 410, -1));

        btnSimpan.setBackground(new java.awt.Color(255, 102, 102));
        btnSimpan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 241, 80, 30));

        btnHapus.setBackground(new java.awt.Color(255, 204, 0));
        btnHapus.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 241, 80, 30));

        btnBatal.setBackground(new java.awt.Color(0, 255, 204));
        btnBatal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 241, 80, 30));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Bunga", "Nama Bunga", "Warna", "Harga", "Asal", "Stok", "Jenis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.setName("tblData"); // NOI18N
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 780, 190));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Harga Bunga");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Asal Bunga");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Warna Bunga");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Warna Bunga");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void idBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idBActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
    
    }//GEN-LAST:event_namaActionPerformed

    private void cmbWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbWarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbWarnaActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void cmbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisActionPerformed

    }//GEN-LAST:event_cmbJenisActionPerformed
   
   private boolean validasiInput(){
       
       try{
           int ID = Integer.parseInt(idB.getText());
           int Harga = Integer.parseInt(harga.getText());
           int Stok = Integer.parseInt(stok.getText());
           
           if ( ID < 1 || Harga < 1 || Stok < 1){
               JOptionPane.showMessageDialog(null, "ID, Harga, Stok harus lebih dari 0");
               return false;
           }
           
       }catch (NumberFormatException e){
           JOptionPane.showMessageDialog(null, "ID, Harga, Stok harus angka");
           return false;
       }
       return true;
   }
   
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (idB.getText().isEmpty() || nama.getText().isEmpty() || asal.getText().isEmpty() || harga.getText().isEmpty() || stok.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong!");
            return;
        }
        
        if (!validasiInput()){
            return;
        }
        
        try {
            st = cn.createStatement();
            if (btnSimpan.getText().equals("Simpan")){
                String cek = "SELECT * FROM bunga WHERE id='"+idB.getText()+"'";
                            
                rs = st.executeQuery(cek);
                if (rs.next()){
                    JOptionPane.showMessageDialog(null, "Data sudah ada!");
                } else {
                    String sql = "INSERT INTO bunga VALUES ('"+idB.getText()+"', '"+nama.getText()+"', '"+cmbWarna.getSelectedItem().toString()+"', '"+asal.getText()+"', '"+harga.getText()+"', '"+stok.getText()+"', '"+cmbJenis.getSelectedItem().toString()+"')";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
                }
            } else {
                String update = "UPDATE bunga SET nama='"+nama.getText()+"', warna='"+cmbWarna.getSelectedItem().toString()+"', asal = '" + asal.getText() + "',  harga = '" + harga.getText() + "', stok = '" + stok.getText() + "', jenis = '" + cmbJenis.getSelectedItem().toString()+"' WHERE id='"+idB.getText()+"'";
                st.executeUpdate(update);
                JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
                btnSimpan.setText("simpan");   
            }
            Tampil();
            bersih();
            idB.setEditable(true);
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "SQL ERROR");
            e.printStackTrace();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
            if (idB.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Pilih bunga dulu");
                return;
            } else {
                int hapus = JOptionPane.showConfirmDialog(null, "Hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (hapus==0){
                    try{
                        String sql = "DELETE FROM bunga WHERE id='"+idB.getText()+"'";
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                        btnSimpan.setText("Simpan");
                        Tampil();
                        bersih();
                    }catch (Exception e){
                        JOptionPane.showMessageDialog(null, "Ada yang salah!");
                    }
                }
            }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        bersih();
        idB.setEditable(true);
        btnSimpan.setText("Simpan");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked

        idB.setText(tblData.getValueAt(tblData.getSelectedRow(), 0).toString());
        nama.setText(tblData.getValueAt(tblData.getSelectedRow(),1).toString());
        cmbWarna.setSelectedItem(tblData.getValueAt(tblData.getSelectedRow(), 2).toString());
        asal.setText(tblData.getValueAt(tblData.getSelectedRow(), 3).toString());
        harga.setText(tblData.getValueAt(tblData.getSelectedRow(), 4).toString());
        stok.setText(tblData.getValueAt(tblData.getSelectedRow(), 5).toString());
        cmbJenis.setSelectedItem(tblData.getValueAt(tblData.getSelectedRow(), 6).toString());
        idB.setEditable(false);
        btnSimpan.setText("Ubah");
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asal;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JComboBox<String> cmbWarna;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField idB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
