/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo;
import javax.swing.JOptionPane;
import java.sql.*;
//import koneksi.KoneksiDatabase;

/**
 *
 * @author Raudhya Azzahra'
 */
public class register extends javax.swing.JFrame {
   public Statement st;
   public ResultSet rs;
   Connection cn = koneksi.KoneksiDatabase.BukaKoneksi();
   
   public register(){
       initComponents();
       setLocationRelativeTo(this);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();
        txtpassword = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        btnRegis = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(172, 97, 171));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("USER");
        jPanel4.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKembali.setBackground(new java.awt.Color(255, 204, 0));
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        txtpassword.setBackground(new java.awt.Color(172, 97, 171));
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 168, -1));

        lbl3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl3.setText("Username");
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtusername.setBackground(new java.awt.Color(172, 97, 171));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 168, -1));

        lbl4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl4.setText("Password");
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        btnRegis.setBackground(new java.awt.Color(255, 102, 102));
        btnRegis.setForeground(new java.awt.Color(255, 255, 255));
        btnRegis.setText("Daftar");
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 330, 200));

        lbl2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("REGISTER");
        jPanel4.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        String username = txtusername.getText();
        String password = txtpassword.getText();
        
        if ( username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
            return;
        }
        
        if (username.length()< 5 || password.length() < 5){
            JOptionPane.showMessageDialog(null, "Panjang username dan password minimal 5");
            return;
        }
        
        
    if ( cn != null){
        try {
            
              st = cn.createStatement();
              String cek = "SELECT * FROM akun WHERE username='"+username+"'";
              rs = st.executeQuery(cek);
              if (rs.next()){
                  JOptionPane.showMessageDialog(null, "Username telah digunakan!");
              } else{
                    String regis = "INSERT INTO akun VALUES ('"+username+"', '"+password+"')";
                    st.executeUpdate(regis);
                    JOptionPane.showMessageDialog(null, "Registrasi berhasil!");
                    this.setVisible(false);
                    new login_user().setVisible(true);
              }
            st.close();
            rs.close();
            cn.close();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "SQL ERROR");
            e.printStackTrace();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR");
            e.printStackTrace();
        }
//        String username = txtusername.getText();
//        String password = txtpassword.getText();
//        
//        if (username.isEmpty() || password.isEmpty()){
//            JOptionPane.showMessageDialog(this, "Tidak boleh kosong");
//            return;
//        }
//        
//        if (username.length() < 5 || password.length() < 5){
//            JOptionPane.showMessageDialog(null, "Panjang username dan password minimal 5");
//            return;
//        }
//        
//        if (cn != null){
//        try{
//            st = cn.createStatement();
//            String cek = "SELECT * FROM akun WHERE username='"+txtusername.getText()+"'";
//            rs = st.executeQuery(cek);
//            if (rs.next()){
//                JOptionPane.showMessageDialog(null, "Username sudah digunakan!");
//            } else {
//                String regis = "INSERT INTO akun VALUES ('"+username+"', '"+password+"')";
//                st.executeUpdate(regis);
//                JOptionPane.showMessageDialog(this, "Registrasi Berhasil !!");
//                this.setVisible(false);
//                new login_user().setVisible(true);
//            }
//            rs.close();
//            st.close();
//            cn.close();
//            
//        }catch (SQLException e){
//            JOptionPane.showMessageDialog(null, "SQL ERROR");
//            e.printStackTrace();
//        }catch (Exception e){
//            JOptionPane.showMessageDialog(null, "ERROR");
//            e.printStackTrace();
//            }    
//        }
        }
    }//GEN-LAST:event_btnRegisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRegis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
